version: 0.1

# Test comment

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - go get -d ./...
      - echo dependencies installed on `date`
  build:
    commands:
      - echo Build strated on `date`
      - echo Compiling the Go code...
      - GOOS=linux go build
  post_build:
    commands:
      - echo Build completed on `date`
artefacts:
    files:
      - dtd-server

