version: 0.1

# Test comment

phases:
  install:
    commands:
      - echo Installing dependencies...
      - go get -d ./...
      - echo dependencies installed on `date`
  pre_build:
    commands:
      - echo This is where tests would be executed...
  build:
    commands:
      - echo Build strated on `date`
      - echo Compiling the Go code...
      - GOOS=linux go build -o dtd-server
  post_build:
    commands:
      - ls -l
      - echo Build completed on `date`
artifacts:
    files:
      - dtd-server
    discard-paths: no
